### ISSUE TITLE
The property play/pause is confusing to me.

### ISSUE THREAD

**Issue by dhylands** [freaktechnik/sonos-adapter#4]
I think that the property should just be called playing. Since the property is a boolean, I think it should just be called "Playing", since a value of true means playing, and a value of false means paused.

Or perhaps it should use an enum instead, with playing and paused as the 2 values of the enum.

**Comment by freaktechnik** [comment]
Optimally the gateway would show a nice play or pause button depending on the state ;) I don't think an enum is well suited for this, personally (you end up with many states (playing can pause, playing can stop, buffering, empty, paused etc.) I think apart from the label this is something that should be solved on the capabilities level.
